
// success codes
export enum SuccessCode {
  EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  EMAIL_RESEND_SUCCESS = 'EMAIL_RESEND_SUCCESS',
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  USER_DATA_RETRIEVED = 'USER_DATA_RETRIEVED',
  PASSWORD_RESET_EMAIL_SENT = 'PASSWORD_RESET_EMAIL_SENT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  AVATAR_UPDATED = 'AVATAR_UPDATED',
  AUTH_TOKEN_REFRESHED_SUCCESSFULY = 'AUTH_TOKEN_REFRESHED_SUCCESSFULY',
  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  ORGANIZATION_DATA_RETRIEVED = 'ORGANIZATION_DATA_RETRIEVED',
  ORGANIZATION_UPDATED = 'ORGANIZATION_UPDATED',
  ORGANIZATION_DELETED = 'ORGANIZATION_DELETED',
  ORGANIZATION_MEMBERS_RETRIEVED = 'ORGANIZATION_MEMBERS_RETRIEVED',
  MEMBER_ADDED_TO_ORGANIZATION = 'MEMBER_ADDED_TO_ORGANIZATION',
  MEMBER_REMOVED_FROM_ORGANIZATION = 'MEMBER_REMOVED_FROM_ORGANIZATION',
  MEMBER_ROLE_UPDATED = 'MEMBER_ROLE_UPDATED',
  JOIN_REQUEST_CREATED = 'JOIN_REQUEST_CREATED',
  JOIN_REQUEST_STATUS_UPDATED = 'JOIN_REQUEST_STATUS_UPDATED',
  // ...
  // add more as needed
}

// error codes
export enum ErrorCode {
  EMAIL_VERIFICATION_INVALID = 'EMAIL_VERIFICATION_INVALID',
  EMAIL_VERIFICATION_EXPIRED = 'EMAIL_VERIFICATION_EXPIRED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  FORBIDDEN = 'FORBIDDEN',
  PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID',
  PASSWORD_RESET_TOKEN_EXPIRED = 'PASSWORD_RESET_TOKEN_EXPIRED',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  ORGANIZATION_ALREADY_EXISTS = 'ORGANIZATION_ALREADY_EXISTS',
  ORGANIZATION_ID_INVALID = 'ORGANIZATION_ID_INVALID',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  JOIN_REQUEST_NOT_FOUND = 'JOIN_REQUEST_NOT_FOUND',
  JOIN_REQUEST_ALREADY_EXISTS = 'JOIN_REQUEST_ALREADY_EXISTS',
  JOIN_REQUEST_ALREADY_PROCESSED = 'JOIN_REQUEST_ALREADY_PROCESSED',
  MEMBBER_DONT_HAVE_PERMISSION = 'MEMBBER_DONT_HAVE_PERMISSION',
  MEMBER_ROLE_INVALID = 'MEMBER_ROLE_INVALID',
  USER_ID_OR_ORGANIZATION_ID_INVALID = 'USER_ID_OR_ORGANIZATION_ID_INVALID',
  USER_IS_NOT_MEMBER_OF_ORGANIZATION = 'USER_IS_NOT_MEMBER_OF_ORGANIZATION',
  // add more as needed
}
