export enum SuccessCode {
  EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  EMAIL_RESEND_SUCCESS = 'EMAIL_RESEND_SUCCESS',
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  USER_DATA_RETRIEVED = 'USER_DATA_RETRIEVED',
  PASSWORD_RESET_EMAIL_SENT = 'PASSWORD_RESET_EMAIL_SENT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  AUTH_TOKEN_REFRESHED_SUCCESSFULY = 'AUTH_TOKEN_REFRESHED_SUCCESSFULY',
}

export enum ErrorCode {
  EMAIL_VERIFICATION_INVALID = 'EMAIL_VERIFICATION_INVALID',
  EMAIL_VERIFICATION_EXPIRED = 'EMAIL_VERIFICATION_EXPIRED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_WAS_BANNED = 'USER_WAS_BANNED',
  PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID',
}
